### ISSUE TITLE
Copy/Paste image from ppt doesn't work 

### ISSUE THREAD

**Issue by rubyzhao** [automeris-io/WebPlotDigitizer#301]
One figure was imported to Powerpoint long time ago. Now I open the ppt and copy the figure and paste it to https://apps.automeris.io/wpd/ in Chrome.  The "Processing..." will come out and stay there for ever, but the figure will not show out.

**Comment by ankitrohatgi** [comment]
Hi, does this happen on Windows or Mac? Does this still happen if you take a screenshot instead of copy+pasting the image?
